---
# Grafana LGTM Stack Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-lgtm
  namespace: default
spec:
  type: NodePort
  selector:
    app: grafana-lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
---
# Datasource Provisioning Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-provisioning
  namespace: default
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s
      - name: Loki
        type: loki
        access: proxy
        url: http://localhost:3100
        editable: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://localhost:3200
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: Loki
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: Prometheus
          serviceMap:
            datasourceUid: Prometheus
          lokiSearch:
            datasourceUid: Loki
---
# Dashboard Provisioning Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  namespace: default
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Online Boutique'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
# Grafana LGTM Stack Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-lgtm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-lgtm
  template:
    metadata:
      labels:
        app: grafana-lgtm
    spec:
      containers:
        - name: grafana-lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000
              name: grafana
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: datasource-provisioning
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: storage
          emptyDir: {}
        - name: datasource-provisioning
          configMap:
            name: grafana-datasource-provisioning
        - name: dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: dashboards
          configMap:
            name: grafana-dashboards
