apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: boutique
spec:
  metrics:
    - name: http-success-rate
      interval: 30s
      count: 3
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            (
              sum(rate(nginx_ingress_controller_requests{
                ingress="frontend",
                status!~"5.."
              }[1m]))
              /
              sum(rate(nginx_ingress_controller_requests{
                ingress="frontend"
              }[1m]))
            )
